import { StyleSheet } from "react-native";
import { theme } from "../../global/themes";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    paddingBottom: 30,
  },
  header: {
    backgroundColor: theme.colors.primaryLight,
    alignItems: "center",
    paddingTop: 44,
    paddingBottom: 30,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  backButton: {
    position: "absolute",
    top: 44,
    left: 16,
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 10,
    borderWidth: 3,
    borderColor: "#fff",
  },
  name: {
    fontSize: 22,
    fontWeight: "bold",
    color: theme.colors.textLight,
  },
  email: {
    fontSize: 14,
    color: theme.colors.textLight,
    opacity: 0.85,
  },
  socialStats: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.16)",
    borderRadius: 16,
    marginTop: 16,
    paddingVertical: 10,
    paddingHorizontal: 18,
  },
  socialItem: {
    alignItems: "center",
    minWidth: 86,
  },
  socialValue: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  socialLabel: {
    color: "#e7fffb",
    fontSize: 12,
    marginTop: 2,
  },
  socialDivider: {
    width: 1,
    height: 34,
    backgroundColor: "rgba(255,255,255,0.35)",
    marginHorizontal: 8,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 20,
    paddingHorizontal: 12,
  },
  card: {
    backgroundColor: "#fff",
    width: 104,
    height: 100,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
    borderWidth: 1,
    borderColor: "#eef3f1",
  },
  cardValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: theme.colors.primaryDark,
  },
  cardLabel: {
    fontSize: 12,
    color: "#666",
    marginTop: 4,
  },
  cardHint: {
    color: theme.colors.primaryLight,
    fontSize: 11,
    fontWeight: "bold",
    marginTop: 5,
  },
  ecoBenefitShortcut: {
    marginHorizontal: 20,
    marginTop: 18,
    backgroundColor: theme.colors.primaryDark,
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  ecoBenefitIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.colors.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  ecoBenefitTextBox: {
    flex: 1,
  },
  ecoBenefitTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  ecoBenefitText: {
    color: "#e7fffb",
    lineHeight: 18,
    marginTop: 3,
  },
  impactBox: {
    margin: 20,
    padding: 20,
    borderRadius: 16,
    backgroundColor: theme.colors.primaryDark,
  },
  impactHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  impactTitle: {
    color: theme.colors.textLight,
    fontSize: 16,
    fontWeight: "bold",
  },
  impactText: {
    color: theme.colors.textLight,
    marginTop: 8,
    lineHeight: 20,
  },
  actions: {
    marginHorizontal: 20,
    marginTop: 6,
  },
  ecoBenefitButton: {
    backgroundColor: theme.colors.primaryLight,
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  ecoBenefitButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  button: {
    backgroundColor: theme.colors.button,
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 10,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  buttonSecondary: {
    borderWidth: 1,
    borderColor: theme.colors.primaryLight,
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
  },
  buttonTextSecondary: {
    color: theme.colors.primaryLight,
    fontWeight: "bold",
  },
  postsSection: {
    marginTop: 22,
    paddingHorizontal: 20,
  },
  postsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  postsTitle: {
    color: theme.colors.primaryDark,
    fontSize: 20,
    fontWeight: "bold",
  },
  postsSubtitle: {
    color: "#666",
    marginTop: 3,
  },
  newPostButton: {
    backgroundColor: theme.colors.primaryLight,
    borderRadius: 12,
    paddingVertical: 9,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  newPostButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  postCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#edf1ef",
    marginBottom: 14,
    elevation: 2,
  },
  postImage: {
    width: "100%",
    height: 220,
  },
  postBody: {
    padding: 14,
  },
  postCaption: {
    color: theme.colors.textDark,
    lineHeight: 20,
  },
  postStats: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginTop: 12,
  },
  postStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  postStatText: {
    color: "#666",
    fontWeight: "600",
    fontSize: 13,
  },
    logout: {
    marginHorizontal: 20,
    marginTop: 30,
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    backgroundColor: theme.colors.primaryDark,
  },
  logoutText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
});
